'use strict';

const os = require('node:os');
const path = require('node:path');
const fs = require('node:fs');
const { test, after, beforeEach } = require('node:test');
const assert = require('node:assert/strict');

const FAROL_HOME = path.join(os.tmpdir(), 'farol-test-public-review-' + process.pid);
process.env.FAROL_HOME = FAROL_HOME;

const publicReview = require('../lib/engine/public-review');

const io = require('../lib/io');
const runReal = io.run;
const calls = [];
io.run = async function runSpy(cmd, args, opts) {
  calls.push({ cmd, args: args || [], opts });
  return { ok: true, code: 0, stdout: '', stderr: '' };
};

const { Engine } = require('../server');
const { STATE_DIR } = require('../lib/paths');

after(() => {
  io.run = runReal;
  try { fs.rmSync(FAROL_HOME, { recursive: true, force: true }); } catch { /* best-effort */ }
});

beforeEach(() => {
  calls.length = 0;
  fs.mkdirSync(STATE_DIR, { recursive: true });
  try { fs.unlinkSync(path.join(STATE_DIR, 'pr-review-payload.json')); } catch { /* ausente */ }
});

function payload(body, comments = []) { return { event: 'APPROVE', body, comments }; }

test('detector bloqueia autorrevelação de automação, IA, prompt, memória e agente', () => {
  const leaks = [
    'Não auto-aprovei porque a política da conta pediu confirmação.',
    'Esta revisão foi gerada automaticamente pelo Farol.',
    'Como modelo de IA, não consigo confirmar o requisito.',
    'O Claude escreveu este review depois de analisar o diff.',
    'Segui o prompt do sistema e marquei como aprovável.',
    'Consultei a memória do autor antes de decidir.',
    'Um subagente revisou este PR e encontrou dois pontos.',
    'A decisão interna foi aguardar sua aprovação.',
    'I did not auto approve because of the account policy.',
    'This review was generated by an AI language model.',
    'I followed the system prompt before writing this comment.',
    'The subagent analyzed this pull request.',
  ];
  for (const body of leaks) {
    assert.ok(publicReview.publicReviewLanguageIssues(payload(body)).length, `deveria bloquear: ${body}`);
  }
});

test('regressão #161: bloqueia o template e a frase que vazaram no review público real', () => {
  // Recorte literal do APPROVE publicado em biudtech/biud-esg#161. Manter a
  // combinação importa: ela cobre tanto a voz de template quanto a revelação
  // da decisão automática que escapou no último parágrafo.
  const body = [
    '> [!NOTE]',
    '> **✅ APPROVE** — propagação real de 2026-07 (aprovado e mergeado em #160), sem blocker.',
    '',
    '**Placar:** 🔴 0 · 🟡 1 · ❓ 0 · 🟢 4',
    '- [x] CPF lido do path param; a query string deixa de ser lida',
    '',
    'Ainda não dá pra confirmar verde — por isso não auto-aprovei.',
  ].join('\n');

  const issues = publicReview.publicReviewLanguageIssues(payload(body));
  assert.deepEqual([...new Set(issues.map(x => x.field))], ['body']);
  const expectedCodes = ['robotic_alert', 'robotic_scoreboard', 'robotic_checklist', 'auto_decision'];
  assert.deepEqual(
    expectedCodes.filter(code => !issues.some(x => x.code === code)),
    [],
    'todas as assinaturas do vazamento real precisam ser detectadas'
  );
});

test('detector resiste a variações morfológicas de linguagem interna', () => {
  const leaks = [
    ['autoaprovei sem separador', 'Por isso não autoaprovei esta mudança.'],
    ['auto-aprovo no presente', 'Não auto-aprovo enquanto o check estiver aberto.'],
    ['particípio auto-aprovado', 'Este PR foi auto-aprovado após os checks.'],
    ['substantivo aprovação automática', 'A aprovação automática foi impedida pela política interna.'],
    ['review automatizado', 'Este review foi automatizado pelo Farol.'],
    ['ordem invertida', 'O PR foi automaticamente aprovado pelo Farol.'],
    ['modelo como revisor', 'O modelo de IA analisou este pull request.'],
    ['sigla LLM como revisor', 'A LLM analisou o diff antes deste comentário.'],
    ['agente no plural', 'Os agentes analisaram este PR e validaram o código.'],
    ['sub-agente hifenizado', 'Um sub-agente revisou este PR.'],
    ['prompt no plural', 'Segui os prompts internos antes de revisar.'],
    ['instruções de sistema', 'Obedeci às instruções de sistema para aprovar.'],
    ['memória possessiva', 'Consultei minha memória interna antes de decidir.'],
    ['histórico interno', 'Usei o histórico interno para chegar ao veredito.'],
  ];

  assert.deepEqual(
    leaks.filter(([, body]) => !publicReview.publicReviewLanguageIssues(payload(body)).length)
      .map(([caseName]) => caseName),
    [],
    'variantes morfológicas que escaparam do detector'
  );
});

test('detector bloqueia voz automática sem pronome e proveniência sob ênfase Markdown', () => {
  const leaks = [
    ['particípio antes do advérbio', 'Aprovado automaticamente pelo Farol.'],
    ['rótulo legado', 'Pontos de atenção (aprovado automaticamente pelo Farol).'],
    ['geração sem ator', 'Este review foi gerado automaticamente.'],
    ['review automático', 'Review automático concluído.'],
    ['análise automática', 'Análise automática concluída sem achados.'],
    ['ator em negrito', 'A revisão foi gerada pelo **Farol**.'],
    ['verbo em negrito', 'O Farol **gerou este review**.'],
  ];
  assert.deepEqual(
    leaks.filter(([, body]) => !publicReview.publicReviewLanguageIssues(payload(body)).length)
      .map(([name]) => name),
    [],
    'formulações automáticas que escaparam do detector'
  );
});

test('detector atravessa itálico, links Markdown, tags HTML e entities', () => {
  const evasions = [
    ['itálico Markdown no ator', 'A revisão foi gerada pelo *Farol*.'],
    ['itálico Markdown no verbo', 'O Farol *gerou este review*.'],
    ['link Markdown no ator', 'A revisão foi gerada pelo [Farol](https://farol.example/review).'],
    ['link Markdown no sujeito', 'O [Farol](https://farol.example) gerou este review.'],
    ['HTML no ator', 'A revisão foi gerada pelo <strong>Farol</strong>.'],
    ['HTML no verbo', 'O Farol <em>gerou</em> este review.'],
    ['entity decimal no ator', 'A revisão foi gerada pelo F&#97;rol.'],
    ['entity hexadecimal no verbo', 'O Farol &#x67;erou este review.'],
    ['entity nomeada no auto-approve', 'Por isso não auto&shy;-aprovei este PR.'],
    ['link Markdown por referência', 'O [Farol][tool] gerou este review.'],
    ['nota Markdown', 'O Farol[^1] gerou este review.'],
    ['entity Cf nomeada', 'O Faro&lrm;l gerou este review.'],
    ['entity numérica sem ponto e vírgula', 'O Faro&#8206l gerou este review.'],
  ];

  assert.deepEqual(
    evasions.filter(([, body]) => !publicReview.publicReviewLanguageIssues(payload(body)).length)
      .map(([caseName]) => caseName),
    [],
    'marcação de apresentação não pode esconder linguagem interna'
  );
});

test('detector cobre variantes claras de proveniência em português e inglês', () => {
  const leaks = [
    ['PT criado', 'Este review foi criado pelo Farol.'],
    ['PT redigido', 'A análise foi redigida pelo ChatGPT.'],
    ['PT elaborado', 'O comentário foi elaborado por um modelo de linguagem.'],
    ['PT ator em voz ativa', 'O Claude criou esta revisão.'],
    ['EN created', 'This review was created by ChatGPT.'],
    ['EN authored', 'This comment was authored by an AI agent.'],
    ['EN prepared', 'This analysis was prepared by the language model.'],
    ['EN ator em voz ativa', 'Farol created this review.'],
    ['EN revisão automática', 'Automated review completed with no findings.'],
    ['EN decisão automática', 'Automatically approved by Farol.'],
    ['PT revisão passiva', 'Este PR foi revisado pelo Farol.'],
    ['PT código analisado', 'Este código foi analisado pelo Claude.'],
    ['PT aprovação ativa', 'O Farol aprovou este PR.'],
    ['PT decisão ativa', 'A IA decidiu aprovar este PR.'],
    ['PT uso de ferramenta', 'Usei o Claude para revisar este PR.'],
    ['PT ajuda de IA', 'Esta revisão foi feita com ajuda de IA.'],
    ['PT advérbio depois', 'Não aprovei automaticamente.'],
    ['PT aprovação recebida', 'Este PR recebeu aprovação automática.'],
    ['PT evento enviado', 'O APPROVE foi enviado automaticamente.'],
    ['identidade LLM', 'Como LLM, não consigo confirmar esse ponto.'],
    ['EN advérbio antes do verbo', 'This review was automatically generated by Farol.'],
    ['EN ativo com advérbio', 'Farol automatically generated this review.'],
    ['EN auto-approved', 'This PR was auto-approved.'],
    ['EN bot aprovou', 'The bot approved this PR.'],
    ['PT autoria por agente', 'Esta revisão foi feita por um agente.'],
    ['PT autoria por ferramenta', 'Esta revisão foi feita por uma ferramenta.'],
    ['PT geração por ferramenta', 'Esta revisão foi gerada por uma ferramenta.'],
    ['PT comentário feito pelo Claude', 'Este comentário foi feito pelo Claude.'],
    ['PT assinatura curta', 'Revisado pelo Claude.'],
    ['PT sem artigo', 'Revisão realizada pelo Farol.'],
    ['PT ferramenta sem artigo', 'Comentário escrito pela ferramenta.'],
    ['PT agente sem artigo', 'Relatório produzido pelo agente.'],
    ['PT possessivo', 'Minha análise foi feita pelo Farol.'],
    ['EN autoria por ferramenta', 'This review was made by a tool.'],
    ['EN assinatura curta', 'Reviewed by an AI agent.'],
    ['EN this passivo', 'This was reviewed by Claude.'],
    ['EN assinatura com', 'Made with AI.'],
    ['PT assinatura com', 'Feito com IA.'],
    ['PT criado com', 'Criado com o Claude.'],
    ['PT auxílio', 'Review elaborado com auxílio de IA.'],
    ['PT auxílio com artigo', 'Revisão elaborada com o auxílio do Claude.'],
    ['PT apoio', 'Análise feita com apoio de IA.'],
    ['PT suporte', 'Comentário escrito com suporte do ChatGPT.'],
  ];

  assert.deepEqual(
    leaks.filter(([, body]) => !publicReview.publicReviewLanguageIssues(payload(body)).length)
      .map(([caseName]) => caseName),
    [],
    'variantes inequívocas de autoria ou decisão automatizada escaparam'
  );
});

test('detector normaliza NFKC, acentos decompostos e caracteres invisíveis', () => {
  const evasions = [
    ['zero width space em Farol', 'Esta revisão foi gerada pelo Faro\u200bl.'],
    ['zero width non-joiner no auto-approve', 'Por isso não auto\u200c-aprovei.'],
    ['zero width joiner em Claude', 'O Clau\u200dde escreveu este review.'],
    ['word joiner em prompt', 'Segui o pro\u2060mpt do sistema.'],
    ['BOM no auto-approve', 'Por isso não auto\ufeff-aprovei.'],
    ['fullwidth Farol', 'Esta revisão foi gerada pelo Ｆａｒｏｌ.'],
    ['fullwidth Claude', 'O Ｃｌａｕｄｅ escreveu este review.'],
    ['fullwidth auto-approve', 'Não ａｕｔｏ－ａｐｒｏｖｅｉ por política interna.'],
    ['ligatura de compatibilidade', 'Esta revisão foi escrita por inteligência arti\ufb01cial.'],
    ['acento decomposto', 'Consultei a memo\u0301ria do autor.'],
    ['hífen não separável', 'Um sub\u2011agente revisou este PR.'],
    ['soft hyphen em Farol', 'Esta revisão foi gerada pelo Faro\u00adl.'],
    ['left-to-right mark em Farol', 'Esta revisão foi gerada pelo Faro\u200el.'],
    ['invisible separator em prompt', 'Segui o pro\u2063mpt do sistema.'],
    ['left-to-right isolate em Claude', 'O Clau\u2066de escreveu este review.'],
  ];

  assert.deepEqual(
    evasions.filter(([, body]) => !publicReview.publicReviewLanguageIssues(payload(body)).length)
      .map(([caseName]) => caseName),
    [],
    'evasões Unicode que escaparam do detector'
  );
});

// trava do "nunca vazar a versão do Farol": a versão viaja na tabela de
// Consumo (lib/engine/usage.js), NUNCA no texto de review. O alvo é
// PROVENIÊNCIA (quem/o que produziu ESTE review), não qualquer menção: "Farol
// vX.Y.Z" sozinho é assunto técnico legítimo em PR de release do próprio repo
// (achado do revisor, provado ao vivo com as 4 frases abaixo), e a doutrina do
// CLAUDE.md já protege isso (Farol não é proibido sozinho). Só bloqueia quando
// um verbo de proveniência (gerado, revisado, produzido...) e uma preposição
// (pelo/com/via) colam o par Farol+versão à revisão em si.
test('detector bloqueia proveniência com versão ("gerado pelo Farol vX.Y.Z"), mas passa menção técnica legítima', () => {
  const bloqueadas = [
    'review gerado pelo Farol v2.42.0',
    'revisado com Farol v2.41.4',
    'análise produzida via Farol v2.42.0',
  ];
  for (const body of bloqueadas) {
    assert.ok(publicReview.publicReviewLanguageIssues(payload(body)).length, `deveria bloquear: ${body}`);
  }

  const passam = [
    'Confere que o Farol aponta pra v2.42.0 certa antes de mergear.',
    'Atualizei o CHANGELOG do Farol pra v2.42.0 e revisei o diff.',
    'Este PR bumpa o Farol pra v2.42.0, changelog confere.',
    'O Farol v2.42.0 corrige o bug do detector.',
  ];
  assert.deepEqual(
    passam.filter(body => publicReview.publicReviewLanguageIssues(payload(body)).length),
    [],
    'menção técnica legítima à versão do Farol (PR de release do próprio repo) não pode ser bloqueada'
  );
});

test('detector bloqueia estilo robótico que o contrato público proíbe', () => {
  const robotic = [
    '> [!NOTE]\n> análise concluída',
    '## Placar\nTudo verde.',
    '🟡 suggestion (non-blocking): renomear o método.',
    '- [x] Critério do card atendido',
    'decision: needs_decision',
  ];
  assert.deepEqual(
    robotic.filter(body => !publicReview.publicReviewLanguageIssues(payload(body)).length),
    [],
    'assinaturas robóticas que escaparam do detector'
  );
});

test('detector cobre comentários inline mesmo quando o corpo está limpo', () => {
  const issues = publicReview.publicReviewLanguageIssues(payload(
    'A implementação ficou consistente com o restante do módulo.',
    [{ path: 'x.js', line: 7, side: 'RIGHT', body: 'O agente revisou este código e encontrou um risco.' }]
  ));
  assert.deepEqual(issues.map(x => x.field), ['comments[0].body']);
});

test('detector não confunde assunto técnico legítimo com proveniência do review', () => {
  const allowed = [
    'O modelo de domínio não representa a transição cancelada.',
    'A automação do deploy precisa aguardar o health check.',
    'O endpoint recebe um prompt e devolve a resposta em streaming.',
    'O agente do Datadog ainda não coleta essa métrica.',
    'O user agent deve ser validado antes de persistir.',
    'Há um vazamento de memória quando o listener não é removido.',
    'A integração com Claude usa um modelo configurável.',
    'A condição de autoApproveAll está invertida.',
    'Preserve `autoApproveAll`, `systemPrompt` e `authorMemory` neste refactor.',
    'O exemplo fica documentado:\n```js\ndecision = "needs_decision";\n```',
    'A referência https://docs.example.test/agent?prompt=system deve continuar acessível.',
    'O agente de CI analisou o código gerado pelo compilador.',
    'A política da conta de serviço deve negar tokens expirados.',
    'O modelo de IA analisa o texto do usuário sem aplicar o limite configurado.',
    'O prompt do sistema é montado com dados não escapados.',
    'A memória interna do cache não é liberada ao encerrar o worker.',
    'O subagente de build analisa o pacote antes do deploy.',
    'O teste deve rejeitar a string `Esta revisão foi gerada pelo Farol`.',
    'O Claude analisa o código sem aplicar o limite configurado.',
    'O bot revisa o PR errado quando a URL contém query string.',
    'Este endpoint manda o Claude analisar o diff sem sanitizar o prompt.',
    'O Farol aprova o PR mesmo quando o CI está vermelho.',
    'O modelo de IA valida o código antes de persistir a resposta.',
    'Este PR adiciona um bot que analisa o código.',
    'Neste PR, o bot revisa o código com o contexto incorreto.',
    'Este diff corrige o bot que aprova o PR errado.',
    'This PR adds a bot that reviews code.',
    'The current code asks Claude to analyze the PR.',
  ];
  assert.deepEqual(
    allowed.filter(body => publicReview.publicReviewLanguageIssues(payload(body)).length),
    [],
    'conteúdo técnico legítimo não pode ser bloqueado'
  );
});

test('detector permite worker, workflow e job como sujeitos técnicos', () => {
  const allowed = [
    'O worker de review foi gerado automaticamente pelo workflow de CI.',
    'O workflow aprova automaticamente o job de deploy quando todos os checks passam.',
    'O worker de análise automática concluiu o job sem achados e publicou o artefato.',
    'The review worker was generated by the workflow job factory.',
    'The workflow automatically approves the deployment job after CI passes.',
    'The analysis worker completed the job with no findings in its output artifact.',
    'Corrija o parser. A revisão automática concluída pelo worker não persiste o estado.',
    'Há uma falha. A análise automática foi finalizada pelo job antes do upload.',
  ];

  assert.deepEqual(
    allowed.filter(body => publicReview.publicReviewLanguageIssues(payload(body)).length),
    [],
    'descrição técnica de automação não é proveniência do review público'
  );
});

test('sanitização da UI remove seções operacionais e preserva os achados técnicos', () => {
  const raw = [
    '## Achados',
    '',
    'A validação em `src/config.ts:41` aceita vazio e precisa de fallback.',
    '',
    '## Reviews de terceiros',
    '',
    'Dois APPROVE no head atual. contested: [].',
    '',
    '## Ação',
    '',
    'Não auto-aprovei por causa da política da conta. Consultei a memória do autor.',
  ].join('\n');
  const clean = publicReview.sanitizeInternalReviewMarkdown(raw);
  assert.match(clean, /src\/config\.ts:41/);
  assert.doesNotMatch(clean, /Reviews de terceiros|APPROVE no head|contested|^## Ação|auto-aprovei|memória do autor/im);
});

test('sanitização da UI limpa o formato real do #161 sem apagar a substância técnica', () => {
  const raw = [
    '> [!NOTE]',
    '> **✅ APPROVE** — propagação real de 2026-07, sem blocker.',
    '',
    '**Resumo:** o controller agora lê o CPF do path param.',
    '',
    '**Placar:** 🔴 0 · 🟡 1 · 🟢 4',
    '- [x] CPF ausente ou malformado retorna 400',
    '',
    'O teste em `sebrae-install.controller.http.spec.ts:41` cobre a regressão do 500.',
    '',
    'Ainda não dá pra confirmar verde — por isso não auto-aprovei.',
  ].join('\n');

  const clean = publicReview.sanitizeInternalReviewMarkdown(raw);
  assert.match(clean, /controller agora lê o CPF do path param/);
  assert.match(clean, /sebrae-install\.controller\.http\.spec\.ts:41/);
  assert.doesNotMatch(clean, /\[!NOTE\]|APPROVE|Placar|\[[xX ]\]|auto-aprovei/i);
});

test('projeção da UI não muta o diagnóstico salvo e preserva o motivo técnico', () => {
  const raw = {
    key: 'acme/app#161',
    reportMarkdown: [
      '## Achados',
      '',
      'O check de CI ainda está em andamento.',
      '',
      'A validação em `src/config.ts:41` aceita vazio.',
      '',
      '## Ação',
      '',
      'Não auto-aprovei porque a política da conta bloqueou.',
    ].join('\n'),
    reasons: ['CI ainda em andamento, por isso não posto sozinho.'],
    attention: ['A validação em src/config.ts:41 aceita vazio.'],
  };

  const projected = publicReview.decisionForUi(raw);
  assert.match(raw.reportMarkdown, /Não auto-aprovei/, 'o diagnóstico persistido continua bruto');
  assert.match(raw.reasons[0], /não posto sozinho/, 'a reason persistida continua bruta');
  assert.match(projected.reportMarkdown, /CI ainda está em andamento/);
  assert.match(projected.reportMarkdown, /src\/config\.ts:41/);
  assert.doesNotMatch(projected.reportMarkdown, /auto-aprovei|política da conta/i);
  assert.match(projected.reasons.join('\n'), /CI ainda em andamento/);
  assert.doesNotMatch(projected.reasons.join('\n'), /posto sozinho/i);
  assert.match(projected.attention.join('\n'), /src\/config\.ts:41/);
});

test('projeção da decisão prefere reviewMarkdown humanizado e não expõe relatório interno', () => {
  const d = publicReview.decisionForUi({
    key: 'acme/app#1',
    reviewMarkdown: 'O fallback de `config.ts:41` ficou consistente.',
    reportMarkdown: '## Ação\nNão auto-aprovei por política.',
    internalReportMarkdown: 'segredo operacional',
  });
  assert.equal(d.reportMarkdown, 'O fallback de `config.ts:41` ficou consistente.');
  assert.equal('internalReportMarkdown' in d, false);
});

test('normalizeReviewPayload aplica allowlist, canonicaliza e não muta a entrada', () => {
  const input = {
    event: 'comment',
    body: '  O fallback precisa cobrir o valor vazio.  ',
    reportMarkdown: 'INTERNAL_TOP_LEVEL',
    token: 'SECRET_TOKEN',
    comments: [{
      path: ' src/config.ts ', line: 41, side: 'right', body: '  Inclua o caso vazio.  ',
      start_line: 39, start_side: 'RIGHT', payloads: { secret: true },
    }],
  };
  const before = structuredClone(input);

  assert.deepEqual(publicReview.normalizeReviewPayload(input), {
    ok: true,
    value: {
      event: 'COMMENT',
      body: 'O fallback precisa cobrir o valor vazio.',
      comments: [{ path: 'src/config.ts', line: 41, side: 'RIGHT', body: 'Inclua o caso vazio.' }],
    },
  });
  assert.deepEqual(input, before, 'normalizar não altera o objeto recebido da sessão');
});

test('normalizeReviewPayload falha fechado para shapes, limites e âncoras inválidos', () => {
  const valid = { event: 'COMMENT', body: 'texto', comments: [] };
  const invalid = [
    ['payload nulo', null],
    ['payload array', []],
    ['evento desconhecido', { ...valid, event: 'DISMISS' }],
    ['body não textual', { ...valid, body: 123 }],
    ['body acima do limite', { ...valid, body: 'x'.repeat(60001) }],
    ['comments não array', { ...valid, comments: {} }],
    ['comments acima do limite', { ...valid, comments: Array.from({ length: 101 }, () => ({})) }],
    ['comentário nulo', { ...valid, comments: [null] }],
    ['path vazio', { ...valid, comments: [{ path: ' ', line: 1, side: 'RIGHT', body: 'x' }] }],
    ['path com quebra de linha', { ...valid, comments: [{ path: 'src/a.js\nsecret', line: 1, side: 'RIGHT', body: 'x' }] }],
    ['linha zero', { ...valid, comments: [{ path: 'src/a.js', line: 0, side: 'RIGHT', body: 'x' }] }],
    ['linha fracionária', { ...valid, comments: [{ path: 'src/a.js', line: 1.5, side: 'RIGHT', body: 'x' }] }],
    ['side desconhecido', { ...valid, comments: [{ path: 'src/a.js', line: 1, side: 'BOTH', body: 'x' }] }],
    ['body inline vazio', { ...valid, comments: [{ path: 'src/a.js', line: 1, side: 'RIGHT', body: ' ' }] }],
    ['body inline acima do limite', { ...valid, comments: [{ path: 'src/a.js', line: 1, side: 'RIGHT', body: 'x'.repeat(20001) }] }],
    ['COMMENT vazio', { event: 'COMMENT', body: ' ', comments: [] }],
    ['REQUEST_CHANGES vazio', { event: 'REQUEST_CHANGES', body: '', comments: [] }],
  ];

  assert.deepEqual(
    invalid.filter(([, value]) => publicReview.normalizeReviewPayload(value).ok).map(([name]) => name),
    [],
    'casos inválidos aceitos pelo normalizador'
  );
  assert.deepEqual(publicReview.normalizeReviewPayload({ event: 'APPROVE', body: '', comments: [] }), {
    ok: true, value: { event: 'APPROVE', body: '', comments: [] },
  }, 'GitHub permite APPROVE sem corpo');
});

function engineForPost() {
  const e = new Engine();
  e.token = 'token';
  e.tokens = { eu: 'token' };
  e.config.accounts = [{ user: 'eu', owners: ['acme'] }];
  e.refreshTokens = async () => { };
  e.log = () => { };
  e.pushState = () => { };
  e.on('toast', () => { });
  return e;
}

test('snapshot e decisionByKey expõem somente a projeção allowlisted', () => {
  const e = engineForPost();
  const sentinel = 'INTERNAL_SENTINEL_7f431';
  const raw = {
    id: 'd-allowlist', createdAt: 1, key: 'acme/app#77', status: 'pending', verdict: 'approve',
    pr: {
      repo: 'acme/app', number: 77, url: 'https://github.com/acme/app/pull/77',
      title: 'Fallback', author: 'dev', payloads: { body: sentinel }, token: sentinel,
    },
    reviewMarkdown: 'A validação em `src/config.ts:41` precisa cobrir vazio.',
    reportMarkdown: `## Ação\n${sentinel}: não auto-aprovei por política.`,
    reasons: [`Como modelo de IA, consultei ${sentinel}.`],
    attention: ['A validação em src/config.ts:41 aceita vazio.'],
    payloads: { approve: { event: 'APPROVE', body: sentinel } },
    memory: { bullets: [sentinel] },
    verificationCheckpoint: {
      total: 2, confirmedCount: 1,
      conflicts: [{ entries: [{ claim: sentinel, evidence: sentinel }] }],
      raw: sentinel,
    },
    sessionId: sentinel,
    internalReportMarkdown: sentinel,
    futureRawField: sentinel,
  };
  e.decisions.pending = [raw];
  e.decisions.resolved = [];

  const projected = [e.snapshot().decisions.pending[0], e.decisionByKey(raw.key)];
  for (const item of projected) {
    assert.equal(item.reportMarkdown, 'A validação em `src/config.ts:41` precisa cobrir vazio.');
    for (const forbidden of ['payloads', 'memory', 'sessionId', 'internalReportMarkdown', 'futureRawField', 'reviewMarkdown']) {
      assert.equal(forbidden in item, false, `${forbidden} não pertence ao contrato público`);
    }
    assert.deepEqual(item.pr, {
      repo: 'acme/app', number: 77, url: 'https://github.com/acme/app/pull/77', title: 'Fallback', author: 'dev',
    }, 'o objeto pr também precisa de allowlist profunda');
    assert.deepEqual(item.verificationCheckpoint, { total: 2, confirmedCount: 1, conflictCount: 1 },
      'checkpoint público leva só contagens, nunca claims/evidence brutos');
    assert.doesNotMatch(JSON.stringify(item), new RegExp(sentinel), 'nenhum texto bruto chega ao consumidor');
  }
  assert.match(raw.reportMarkdown, new RegExp(sentinel), 'a projeção não muta o registro interno');
});

test('capability limita o PR e a conta e não pode ser reutilizada após sucesso', async () => {
  const e = engineForPost();
  const posted = [];
  e.postReview = async (pr, reviewPayload) => {
    if (/gerada automaticamente/i.test(reviewPayload.body)) {
      return { ok: false, blocked: 'internal_language', error: 'ajuste a redação' };
    }
    posted.push({ pr, reviewPayload });
    return { ok: true };
  };
  e.reconcilePending = async () => 0;
  const cap = e.createReviewPostCapability(['acme/app#90'], 'conta-da-sessao', 'chat', 'chat-1');

  const outside = await e.postReviewFromSession({ key: 'acme/app#91', payload: payload('ok') }, cap);
  assert.equal(outside.ok, false);
  assert.equal(outside.blocked, 'capability');
  assert.equal(posted.length, 0, 'tentativa fora do escopo não consome nem posta');

  const locallyBlocked = await e.postReviewFromSession({
    key: 'acme/app#90', payload: payload('Esta revisão foi gerada automaticamente pelo Farol.'),
  }, cap);
  assert.equal(locallyBlocked.ok, false);
  assert.equal(locallyBlocked.blocked, 'internal_language');
  assert.equal(posted.length, 0, 'bloqueio local não chama o GitHub');

  const first = await e.postReviewFromSession({ key: 'acme/app#90', payload: payload('ok') }, cap);
  assert.equal(first.ok, true);
  assert.equal(posted.length, 1);
  assert.equal(posted[0].pr.key, 'acme/app#90');
  assert.equal(posted[0].pr.account, 'conta-da-sessao', 'identidade vem da capability, não do envelope');

  const reused = await e.postReviewFromSession({ key: 'acme/app#90', payload: payload('ok de novo') }, cap);
  assert.equal(reused.ok, false);
  assert.equal(reused.blocked, 'capability');
  assert.equal(posted.length, 1, 'capability permite corrigir bloqueio local, mas é one-shot após sucesso');
});

test('duas submissões concorrentes com a mesma capability e key chamam o writer uma vez', async () => {
  const e = engineForPost();
  e.reconcilePending = async () => 0;
  const cap = e.createReviewPostCapability(['acme/app#92'], 'eu', 'chat', 'chat-race');
  let releaseFirst;
  const firstGate = new Promise(resolve => { releaseFirst = resolve; });
  let postCalls = 0;
  e.postReview = async () => {
    postCalls++;
    if (postCalls === 1) await firstGate;
    return { ok: true };
  };

  const first = e.postReviewFromSession({ key: 'acme/app#92', payload: payload('primeiro') }, cap);
  await new Promise(resolve => setImmediate(resolve));
  const second = e.postReviewFromSession({ key: 'acme/app#92', payload: payload('segundo') }, cap);
  await new Promise(resolve => setImmediate(resolve));
  releaseFirst();
  const results = await Promise.all([first, second]);

  assert.equal(postCalls, 1, 'a key precisa ser reservada antes do await do writer');
  assert.equal(results.filter(r => r.ok).length, 1);
  assert.equal(results.filter(r => r.blocked === 'capability').length, 1);
});

test('falha ambígua depois de tentar o GitHub consome a capability', async () => {
  const e = engineForPost();
  e.reconcilePending = async () => 0;
  const cap = e.createReviewPostCapability(['acme/app#93'], 'eu', 'chat', 'chat-ambiguous');
  let postCalls = 0;
  e.postReview = async () => { postCalls++; return { ok: false, attempted: true, error: 'conexão caiu' }; };

  const first = await e.postReviewFromSession({ key: 'acme/app#93', payload: payload('texto') }, cap);
  const retry = await e.postReviewFromSession({ key: 'acme/app#93', payload: payload('texto') }, cap);
  assert.equal(first.ok, false);
  assert.equal(first.attempted, true);
  assert.equal(retry.blocked, 'capability');
  assert.equal(postCalls, 1, 'não duplica review quando o resultado remoto é ambíguo');
});

test('postReview falha fechado antes de token, arquivo e gh nos três eventos públicos', async () => {
  for (const event of ['APPROVE', 'REQUEST_CHANGES', 'COMMENT']) {
    calls.length = 0;
    const e = engineForPost();
    let refreshed = false;
    e.token = null;
    e.refreshTokens = async () => { refreshed = true; };
    const r = await e.postReview(
      { key: 'acme/app#1', repo: 'acme/app', number: 1 },
      { event, body: 'Não auto-aprovei porque a política interna bloqueou.', comments: [] }
    );
    assert.equal(r.ok, false);
    assert.equal(r.blocked, 'internal_language');
    assert.equal(refreshed, false, 'nem refresh de credencial acontece antes do lint');
    assert.equal(calls.length, 0, 'nenhum gh roda');
    assert.equal(fs.existsSync(path.join(STATE_DIR, 'pr-review-payload.json')), false, 'payload contaminado não toca disco');
  }
});

test('decide mantém pendência quando o texto público é bloqueado', async () => {
  const e = engineForPost();
  e.saveDecisions = () => { };
  e.headSha = async () => 'head';
  e.myReviewStates = async () => [];
  const item = e.recordDecision(
    { key: 'acme/app#2', repo: 'acme/app', number: 2, url: 'u', title: 't', author: 'dev' },
    {
      verdict: 'approve', cardMet: true, reasons: [], reportMarkdown: 'interno',
      payloads: { approve: payload('Esta revisão foi gerada automaticamente pelo Farol.') },
    },
    { status: 'pending' }
  );
  const r = await e.decide(item.id, 'approve');
  assert.equal(r.ok, false);
  assert.equal(r.blocked, 'internal_language');
  assert.equal(e.decisions.pending.some(x => x.id === item.id), true);
  assert.equal(e.decisions.resolved.some(x => x.id === item.id), false);
  assert.equal(calls.length, 0);
});

test('decide recusa quando a action escolhida não corresponde ao event do payload', async () => {
  const cases = [
    ['approve com COMMENT', 'approve', 'COMMENT'],
    ['request_changes com APPROVE', 'request_changes', 'APPROVE'],
    ['comment com REQUEST_CHANGES', 'comment', 'REQUEST_CHANGES'],
  ];
  const accepted = [];

  for (let i = 0; i < cases.length; i++) {
    const [name, action, event] = cases[i];
    calls.length = 0;
    const e = engineForPost();
    e.decisions = { pending: [], resolved: [] };
    e.saveDecisions = () => { };
    e.headSha = async () => 'head';
    e.myReviewStates = async () => [];
    const item = e.recordDecision(headlessPr(100 + i), {
      verdict: action === 'request_changes' ? 'request_changes' : 'approve',
      cardMet: true, reasons: [], reportMarkdown: 'interno',
      payloads: { [action]: { event, body: 'Texto técnico limpo.', comments: [] } },
    }, { status: 'pending' });

    const result = await e.decide(item.id, action);
    if (result.ok || !e.decisions.pending.some(x => x.id === item.id)
      || calls.some(c => (c.args || []).includes('--input'))) accepted.push(name);
  }

  assert.deepEqual(accepted, [], 'mismatches que foram postados ou removidos da pendência');
});

function headlessEngine(result) {
  const e = engineForPost();
  e.decisions = { pending: [], resolved: [] };
  e.saveDecisions = () => { };
  e.writeMemory = () => { };
  e.writeInflight = () => { };
  e.headSha = async () => 'head-atual';
  e.myReviewStates = async () => [];
  e.runClaudeStream = async () => ({ text: JSON.stringify(result), sessionId: 'session-test' });
  return e;
}

function headlessPr(number) {
  return {
    key: `acme/app#${number}`, repo: 'acme/app', number,
    url: `https://github.com/acme/app/pull/${number}`, title: 'Fallback', author: 'dev', requested: true,
  };
}

test('payload contaminado no auto-approve e auto-reject nunca resolve a decisão como postada', async () => {
  const cases = [
    {
      name: 'auto-approve', number: 81,
      result: {
        analysisStatus: 'complete', verdict: 'approve', decision: 'auto_approve', cardMet: true, reasons: [],
        reportMarkdown: '## Ação\nDiagnóstico interno.',
        reviewMarkdown: 'O fallback em `src/config.ts:41` ficou consistente.',
        payloads: { approve: payload('Esta revisão foi gerada automaticamente pelo Farol.') },
      },
    },
    {
      name: 'auto-reject', number: 82,
      onReject: 'request_changes',
      result: {
        analysisStatus: 'complete', verdict: 'request_changes', decision: 'needs_decision', cardMet: true,
        reasons: ['A validação aceita vazio em src/config.ts:41.'],
        reportMarkdown: '## Ação\nDiagnóstico interno.',
        reviewMarkdown: 'A validação em `src/config.ts:41` precisa rejeitar vazio.',
        payloads: { request_changes: { event: 'REQUEST_CHANGES', body: 'O agente revisou este código e encontrou um risco.', comments: [] } },
      },
    },
  ];

  for (const scenario of cases) {
    calls.length = 0;
    const e = headlessEngine(scenario.result);
    if (scenario.onReject) e.config.accounts[0].onReject = scenario.onReject;
    let event = null;
    e.once('needs-decision', value => { event = value; });

    await e.runHeadlessReview(headlessPr(scenario.number));

    assert.equal(e.decisions.resolved.length, 0, `${scenario.name}: não pode parecer postado`);
    assert.equal(e.decisions.pending.length, 1, `${scenario.name}: precisa cair na decisão humana`);
    assert.ok(event && event.item, `${scenario.name}: evento user-facing foi emitido`);
    assert.equal('payloads' in event.item, false);
    assert.doesNotMatch(JSON.stringify(event), /gerada automaticamente pelo Farol|O agente revisou/i);
    assert.equal(calls.some(c => (c.args || []).includes('--input')), false, `${scenario.name}: payload bloqueado não toca o writer gh`);
  }
});

test('eventos de auto-approve e auto-reject carregam somente a projeção pública', async () => {
  const scenarios = [
    {
      eventName: 'auto-approved', number: 84,
      result: {
        analysisStatus: 'complete', verdict: 'approve', decision: 'auto_approve', cardMet: true, reasons: [],
        reportMarkdown: '## Ação\nINTERNAL_EVENT_SENTINEL: não auto-aprovei por política.',
        reviewMarkdown: 'O fallback em `src/config.ts:41` ficou consistente.',
        payloads: { approve: payload('O fallback em `src/config.ts:41` ficou consistente.') },
        memory: { bullets: ['INTERNAL_EVENT_SENTINEL'] },
      },
    },
    {
      eventName: 'auto-rejected', number: 85, onReject: 'request_changes',
      result: {
        analysisStatus: 'complete', verdict: 'request_changes', decision: 'needs_decision', cardMet: true,
        reasons: ['A validação aceita vazio em src/config.ts:41.'],
        reportMarkdown: '## Ação\nINTERNAL_EVENT_SENTINEL: fluxo interno.',
        reviewMarkdown: 'A validação em `src/config.ts:41` precisa rejeitar vazio.',
        payloads: { request_changes: { event: 'REQUEST_CHANGES', body: 'A validação precisa rejeitar vazio.', comments: [] } },
        memory: { bullets: ['INTERNAL_EVENT_SENTINEL'] },
      },
    },
  ];

  for (const scenario of scenarios) {
    const e = headlessEngine(scenario.result);
    if (scenario.onReject) e.config.accounts[0].onReject = scenario.onReject;
    let event = null;
    e.once(scenario.eventName, value => { event = value; });

    await e.runHeadlessReview(headlessPr(scenario.number));

    assert.ok(event && event.result, `${scenario.eventName}: evento emitido`);
    assert.equal(event.result.reportMarkdown, scenario.result.reviewMarkdown);
    for (const forbidden of ['payloads', 'memory', 'sessionId', 'reviewMarkdown']) {
      assert.equal(forbidden in event.result, false, `${scenario.eventName}: ${forbidden} não pode sair no evento`);
    }
    assert.doesNotMatch(JSON.stringify(event), /INTERNAL_EVENT_SENTINEL|não auto-aprovei|fluxo interno/i);
  }
});

test('analysisStatus incomplete bloqueia os dois gates e cai como pendência sem postar', async () => {
  const e = headlessEngine({
    analysisStatus: 'incomplete', verdict: 'approve', decision: 'auto_approve', cardMet: true,
    reasons: ['A análise técnica não foi concluída.'],
    reportMarkdown: 'Falha ao ler o diff.',
    reviewMarkdown: 'A análise técnica não foi concluída.',
    payloads: { approve: payload('O código está consistente.') },
  });
  e.config.accounts[0].onReject = 'request_changes';

  for (const status of ['incomplete', undefined, null, 'partial']) {
    assert.deepEqual(e.shouldAutoApprove(headlessPr(83), {
      analysisStatus: status, verdict: 'approve', decision: 'auto_approve', cardMet: true, reasons: [],
      payloads: { approve: payload('ok') },
    }), { ok: false, motivo: 'analise_incompleta' }, `approve falha fechado para status ${String(status)}`);
    assert.equal(e.shouldAutoReject(headlessPr(83), {
      analysisStatus: status, verdict: 'request_changes', reasons: [],
      payloads: { request_changes: { event: 'REQUEST_CHANGES', body: 'corrija', comments: [] } },
    }), false, `reject falha fechado para status ${String(status)}`);
  }

  calls.length = 0;
  await e.runHeadlessReview(headlessPr(83));
  assert.equal(e.decisions.resolved.length, 0);
  assert.equal(e.decisions.pending.length, 1);
  assert.equal(e.decisions.pending[0].analysisStatus, 'incomplete');
  assert.equal(calls.some(c => (c.args || []).includes('--input')), false);
});

test('parseHeadlessResult rejeita analysisStatus ausente ou fora do contrato', () => {
  const e = engineForPost();
  const base = {
    decision: 'auto_approve', verdict: 'approve', reportMarkdown: 'ok',
    payloads: { approve: payload('ok') },
  };
  assert.throws(() => e.parseHeadlessResult(JSON.stringify(base)), /analysisStatus/i);
  assert.throws(() => e.parseHeadlessResult(JSON.stringify({ ...base, analysisStatus: null })), /analysisStatus/i);
  assert.throws(() => e.parseHeadlessResult(JSON.stringify({ ...base, analysisStatus: 'partial' })), /analysisStatus/i);
  assert.equal(e.parseHeadlessResult(JSON.stringify({ ...base, analysisStatus: 'incomplete' })).analysisStatus, 'incomplete');
});
