// A superfície pública do ui/pure.js é o contrato com o ui/app.js (que importa dezenas de
// nomes num import só) e com os 13 testes que importam daqui. Durante a quebra em
// ui/pure/*.js, nenhum nome pode sumir nem mudar de grafia: a tela quebraria em runtime
// com a suíte possivelmente verde, porque quase nenhum teste chama TODOS os nomes.
//
// Esta lista é CONGELADA de propósito, e é a única do repositório que não deriva do fonte:
// derivar do próprio arquivo que ela protege a tornaria vazia (ela casaria consigo mesma
// depois de qualquer perda). Nome sai daqui só com motivo declarado no commit.
import test from 'node:test';
import assert from 'node:assert/strict';
import { arquivosDosPuros } from './helpers/fontes-ui.js';

const CONGELADA = [
  // outra pessoa revisando e limite do plano no card da fila (02/10/2026): ui/pure/revisando.js
  "avisosDoCard",
  "contasNoLimiteDaFila",
  "horaDoReset",
  "limitNoteHtml",
  "othersLineHtml",
  "pwOthersHtml",
  "queueLimitHtml",
  // controle do celular (28/09/2026): ui/pure/aparelhos-fila.js e ui/pure/aparelhos-painel.js
  // limpeza da v2.65.0: a fila do aparelho usa estes rotulos de compartilhado.js; sairam
  // operacoesRemotasHtml e pendenciasCompartilhadasHtml, que ficaram sem chamador
  "feedDaOperacaoHtml",
  "resumoDaOperacao",
  "textoDoBloqueio",
  "textoDoVeredito",
  // só aparelho que aceitou o controle explicitamente entra na aba Aparelhos (29/09/2026)
  "aparelhosQueAceitam",
  // a política mora só na conta (30/09/2026): saiu `alcanceDaChaveGeral`, que dizia quantas
  // contas cada chave geral da Automação alcançava (as chaves gerais deixaram de existir), e
  // entraram as palavras únicas da política e a leitura por extenso dela
  "POLITICA_DA_CONTA_TEXTOS",
  "politicaDaContaNaTela",
  "VERSAO_DO_CONTROLE",
  "VIVO_MS",
  "avisoDoAparelhoHtml",
  "comandosDoAparelhoHtml",
  "confirmacaoAutomatica",
  "contagemDaFila",
  "contasDoAparelhoHtml",
  "executoresDoConjunto",
  "faixaDeAparelhosHtml",
  "filaDoAparelhoHtml",
  "grupoDoItem",
  "itensDaFila",
  "ligaAutomatico",
  "motivoSemAcao",
  "nenhumExecutorHtml",
  "painelDoAparelhoHtml",
  "retornoDoComando",
  "seusAparelhosHtml",
  "situacaoDaFila",
  "situacaoDoAparelho",
  "versaoAntiga",
  "CHAT_TEXTOS",
  "chatAvisoDaJanela",
  "chatAvisoExportado",
  "chatAvisoFalhaExport",
  "chatCarregandoHtml",
  "chatContagem",
  "chatEnvolverTabelas",
  "chatEstadoDaSessao",
  "chatHora",
  "chatHoraCompleta",
  "chatHoraIso",
  "chatMensagensHtml",
  "analiseImpecavel",
  "DOMAIN_DEFS",
  "DOMLEVEL_OPTS",
  "FAROL_PRE_STAMP_LABEL",
  "FAROL_STAMP_SINCE",
  "MERGE_EM_ANDAMENTO",
  "PAPEL_OPTS",
  "PB_OPTS",
  "PB_SHORT",
  "STAGE_FLOW_ORDER",
  // acompanhamento honesto da revisao (30/09/2026): entraram situacaoDaSessao, etapaAtiva
  // e SEM_SINAL_MS, e SAIU stageLabel, que rotulava a sessao pela idade ("(processando…)"
  // ate 15 s, string vazia depois) e ficou sem chamador quando o cabecalho do cartao
  // passou a mostrar a etapa real estampada pelo engine
  "SEM_SINAL_MS",
  "etapaAtiva",
  "situacaoDaSessao",
  "USAGE_KIND_COLOR",
  "USAGE_KIND_LABEL",
  "USAGE_PALETTE",
  "USAGE_ST_LABEL",
  "accountBarVisible",
  "camposDaEdicao",
  "accountsManagerHtml",
  "acoesDaOperacao",
  "acoesDaRevisao",
  "acoesDoCandidato",
  "addControl",
  "agentsTitle",
  "analysisOpsPlan",
  "andamentoAtrasado",
  "andamentoAtrasadoHtml",
  "aparelhoPoliticaHtml",
  "aparelhoPoliticaParaPublicar",
  "aparelhosAdminHtml",
  "aparelhosAposentarConfirmacao",
  "aparelhosCampoSenhaModal",
  "aparelhosConsentimentoHtml",
  "aparelhosContasNaoCobertas",
  "aparelhosDesignacaoHtml",
  "aparelhosDesignacaoPendente",
  "aparelhosDesignarAcao",
  "aparelhosDesignarConfirmacao",
  "aparelhosLimpezaHtml",
  "aparelhosListaHtml",
  "aparelhosNavegadoresHtml",
  "aparelhosRenomearDialogo",
  "aparelhosResultadoDaLimpeza",
  "aparelhosSecaoHtml",
  "aparelhosSouAdmin",
  "aprovadosHoje",
  "auditoriaLinhaHtml",
  "automacaoPausadaPor",
  "avatar",
  "budgetEditorHtml",
  "buildFixPrompt",
  "canMergeSelfAnalysis",
  "candidatosDoConjuntoHtml",
  "canonicalGithubPrUrl",
  "capacidadesIndisponiveis",
  "capacidadesIndisponiveisHtml",
  "chatBadge",
  "chipHtml",
  "claudeAuthBadge",
  "claudeProfilesHtml",
  "comandoPermitido",
  "comandosEmitidosHtml",
  "compartilhadoBloqueioHtml",
  "creditsHtml",
  "defaultFor",
  "delivActivityCard",
  "delivActivityChart",
  "delivCappedMsg",
  "delivDayBuckets",
  "delivEmptyState",
  "delivFilterItems",
  "delivSliceRows",
  "delivStats",
  "delivStatsCards",
  "deliveriesByAuthor",
  "deliveriesByRepo",
  "diagnosticoHtml",
  "diffVs",
  "domLevelOf",
  "domainMatrix",
  "effectiveHidden",
  "envioDepoisDoLote",
  "envioHistoricoHtml",
  "esc",
  "escAttrSelector",
  "esperaCiCardMeta",
  "estadoDasListas",
  "estadoDoEscopo",
  "expiredSessionMarks",
  "feedLine",
  "filaJustaHtml",
  "falhasSecaoHtml",
  "fjMoeda",
  "fjQuando",
  "fmtClock",
  "fmtCompact",
  "fmtDur",
  "fmtLogStamp",
  "fmtMoney",
  "festasPendentes",
  "fmtRel",
  "fmtSpan",
  "fmtStamp",
  "fmtTok",
  "fmtUsageMetric",
  "fmtWhenDay",
  "genId",
  "ghPrUrl",
  "groupBy",
  "grupoCartaoHtml",
  "grupoCorpoDaRota",
  "grupoCorpoDoGrupo",
  "grupoFormHtml",
  "grupoNovoId",
  "grupoTipoDoPerfil",
  "gruposPerfisHtml",
  "gruposSecaoHtml",
  "hexToRgba",
  "hiddenFootLabel",
  "identidadeDeAparelho",
  "inicioConfirmacao",
  "inicioDialogo",
  "jiraBaseUrlProblema",
  "jiraPrefixosProblema",
  "lastMerge",
  "listViewState",
  "localDayKey",
  "logGroupLine",
  "logGroupRate",
  "logReadingLine",
  "logRegimeLines",
  "logSpanMinutes",
  "logSummaryLines",
  "logSummaryShort",
  "logTailLines",
  "md",
  "mergeToastKind",
  "mesclarListaRemota",
  "meusPrsRemotoHtml",
  "modoDistribuicaoHtml",
  "myPRsEmptyMsg",
  "nomeDoAparelho",
  "notaComandoHtml",
  "notaDistribuicaoHtml",
  "notaTomadaSofridaHtml",
  "oQueELocalHtml",
  "opDismissDelay",
  "opTransition",
  "opcoesDeModeloHtml",
  "operationChecks",
  "ordemDoEscalonador",
  "orgsMonitoradas",
  "overrideFor",
  "ownerFromUrl",
  "panoramaRemotoHtml",
  "panoramaRowHtml",
  "papelOf",
  "papelPicker",
  "parkedNoteHtml",
  "pareamentoHtml",
  "parseGoto",
  "perfilProblemasHtml",
  "perfilTesteHtml",
  "personMention",
  "personOf",
  "plural",
  "prCoordNoteHtml",
  "prIdentificado",
  "prIdentificadoHtml",
  "prKeyFromUrl",
  "prRefMention",
  "pushbackControl",
  "qualityBlockTitle",
  "qualityReasonLabel",
  "queueCardHtml",
  "queueEmptyOkHtml",
  "reRoundBoxHtml",
  "reRoundStatus",
  "reasonGroups",
  "reasonGroupsHtml",
  "reasonText",
  "reciboEstado",
  "reciboFinal",
  "renderOrgBlock",
  "repetirConfirmacao",
  "repoMention",
  "repoShort",
  "reposOfOrg",
  "resolvedRow",
  "reviewBoxHtml",
  "reviewChip",
  "reviewerLabel",
  "revisaoAbertaHtml",
  "opcoesDaDecisao",
  "motivosDaPendenciaHtml",
  "motivosOmitidosDe",
  "botaoDoReviewHtml",
  "payloadsDaRevisaoHtml",
  "revisoesCompartilhadasHtml",
  "runtimeChecks",
  "safeJsonParse",
  "sameSet",
  "selecaoAceitaEsforco",
  "selfAnalysisBadge",
  "selfAnalysisStale",
  "selfAnalysisToggle",
  "selfSessionKey",
  "sessionCardHtml",
  "sessionProgress",
  "sessionRefCell",
  "sessionRefMention",
  "settingsIgnoradasTexto",
  "sparklinePath",
  "splitHiddenPRs",
  "stageFlowFrom",
  "stageFlowHtml",
  "stagesLine",
  "separarPendentes",
  "staleCardMeta",
  "statusBannerHtml",
  "stripFence",
  "suggestDefault",
  "syncAparelhosHtml",
  "syncCfgComGeral",
  "syncCfgSemCompartilhamento",
  "syncChaveHtml",
  "syncClasseCartao",
  "syncConexaoHtml",
  "syncConfirmacaoDoClique",
  "syncConfirmacoesDoClique",
  "syncContaHtml",
  "syncCoordenacaoHtml",
  "syncEnvioHtml",
  "syncEstado",
  "syncOlhoDesenho",
  "syncOlhoHtml",
  "syncOlhoRotulo",
  "syncPrivacidadeHtml",
  "syncSecaoHtml",
  "syncSeloHtml",
  "syncTogglesHtml",
  "sysNorm",
  "textoDaRecusa",
  "tomadasFeitasHtml",
  "toolRefGoto",
  "transferenciaConfirmacao",
  "transferenciaDialogo",
  "updateAdiadoHtml",
  "usageBudgetHtml",
  "usageColorsFor",
  "usageConsolidadoEnvelopeHtml",
  "usageConsolidatedHtml",
  "usageDayKeysBack",
  "usageDelta",
  "usageHoverIndex",
  "usageKpisHtml",
  "usageMatrixHtml",
  "usageMatrixRows",
  "usageMetricVal",
  "usageSessionRow",
  "usageSessionsHtml",
  "usageStackLayers",
  "usageTooltipHtml",
  "validScope",
  "versaoClaudeCheck",
  "visaoCompartilhada",
  "contasGhHtml",
  "contasGhVazio",
  "secoesDaFrota",
];

test('o ui/pure.js exporta exatamente a superficie congelada', async () => {
  const modulo = await import('../ui/pure.js');
  const atual = Object.keys(modulo).sort();
  const sumiram = CONGELADA.filter((n) => !atual.includes(n));
  const nasceram = atual.filter((n) => !CONGELADA.includes(n));
  assert.deepEqual(sumiram, [], 'sumiram nomes da superficie publica do ui/pure.js');
  assert.deepEqual(nasceram, [], 'nomes novos na superficie: acrescente a lista congelada no mesmo commit');
});

test('todo nome exportado e usavel, nao so declarado', async () => {
  // reexport quebrado (arquivo que não existe, nome com grafia errada no `export *`)
  // aparece aqui como undefined, e não como ausência de chave.
  const modulo = await import('../ui/pure.js');
  const indefinidos = CONGELADA.filter((n) => modulo[n] === undefined);
  assert.deepEqual(indefinidos, [], 'nomes exportados com valor undefined');
});

/* Nenhum nome pode estar declarado em DOIS arquivos do ui/pure. Achado durante a própria
   Fase 1a: uma contraprova desfeita com `git checkout` deixou fjQuando e fjMoeda definidos
   no ui/pure.js E num módulo que ninguém importava. A suíte ficou verde, porque arquivo
   órfão não é lido por ninguém, e a duplicata só apareceria quando alguém corrigisse um
   lado só. Derivado do fonte: módulo novo entra na varredura sozinho. */
test('nenhum simbolo exportado do ui/pure esta declarado em dois arquivos', () => {
  const dono = new Map();
  const repetidos = [];
  for (const { nome, texto } of arquivosDosPuros()) {
    for (const m of texto.matchAll(/^export (?:function|const) (\w+)/gm)) {
      if (dono.has(m[1])) repetidos.push(`${m[1]} em ${dono.get(m[1])} e em ${nome}`);
      else dono.set(m[1], nome);
    }
  }
  assert.deepEqual(repetidos, [], 'simbolo declarado em dois arquivos do ui/pure');
  assert.ok(dono.size >= 100, `esperava a maioria dos simbolos declarada, achei ${dono.size}`);
});
